### ISSUE TITLE
I don't use aliyun

### ISSUE THREAD

**Issue by zyl0622** [messense/rocketmq-python#26]
I don't use aliyun，Don't need certification 
How do I get the message status？

**Comment by messense** [comment]
What do you mean by `get the message status`? If you use `Producer.send_sync` you can get status from its return value.

**Comment by zyl0622** [comment]
自己搭建的本地mq集群，不需要认证，调用同步发送报错能得到返回值吗？

发自我的 iPhone

**Comment by messense** [comment]
报错会抛异常。

**Comment by zyl0622** [comment]
是的，是不是不支持非阿里云服务？
发自我的 iPhone

**Comment by messense** [comment]
支持的，但是目前基于 rocketmq-client-cpp 的封装在报错的时候是拿不到具体报错信息的。

**Comment by zyl0622** [comment]
现在同步发送拿不到返回值，报错 这个现在如何解决？

发自我的 iPhone

**Comment by messense** [comment]
贴一下 ~/logs/rocketmq-cpp 文件夹下面最新的日志。

**Comment by zyl0622** [comment]
目前，使用自己搭建的非阿里云的mq服务问题比较多，
得不到发送消息的状态，并且报错，消息发送成功了，但是执行一次发送动作会发送多条一样的消息


是不是因为我把“producer.set_session_credentials('XXX', 'XXXX', 'ALIYUN')”这个认证去掉的关系？


我本地的集群不需要认证




--


         
 
    周亚亮

---------------------------------
手机：18500330983

邮件地址：zhouyaliang0622@126.com


在 2019-03-19 17:28:35，"messense" <notifications@github.com> 写道：


贴一下 ~/logs/rocketmq-cpp 文件夹下面最新的日志。

**Comment by messense** [comment]
应该没有关系。

**Comment by afutureboss** [comment]
我们是自己搭建的rocketmq集群，producer.set_session_credentials('XXX', 'XXXX', 'ALIYUN')这里第三个参数可以不指定吗?,有默认值吗，如果不指定的时候，consumer消费的时候是不是也可以不指定呢？

**Comment by messense** [comment]
@afutureboss 自己搭建的 RocketMQ 集群没有配置授权机制的话可以不调用 `set_session_credentials`

**Comment by messense** [comment]
cc https://github.com/apache/rocketmq-client-cpp/issues/121

**Comment by messense** [comment]
Close as inactive.
