### ISSUE TITLE
producer.set_namesrv_domain('http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet') 使用方法

### ISSUE THREAD

**Issue by heam911** [messense/rocketmq-python#32]
我是一名初学者，初次接触python和erocketmq。
producer.set_namesrv_domain('http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet')
这里可以使用非aliyun的host吗？可否使用ip+port的形式？

**Comment by messense** [comment]
ip + port 可以用 `set_namesrv_addr` 方法。
