### ISSUE TITLE
windows本地调用 出现error 193

### ISSUE THREAD

**Issue by heam911** [messense/rocketmq-python#34]
windows本地模拟的时候，在import rocketmq文件，调用dll，读取librocketmq.so的时候出现异常。windows和python都是64位的，是不是rocketmq的位数只有32位？换成linux 64位 ，python 64位的时候，是不是还是会有这个问题？

**Comment by messense** [comment]
暂时不支持 Windows.

**Comment by messense** [comment]
目前只支持 Linux 和 macOS 64 位 Python 版本。

**Comment by heam911** [comment]
好的。
