### ISSUE TITLE
不知道为什么从 java 端发送的消息 body 一直为空

### ISSUE THREAD

**Issue by qinxiaoxiang** [messense/rocketmq-python#38]
如题，在阿里云控制台下载消息是有内容的，但是使用PushConsumer 时，从 callback 读出来的 body 都为空，tags 和 keys没问题

**Comment by messense** [comment]
贴一下 ~/logs/rocketmq-cpp 文件夹下面最新的日志看看。

**Comment by messense** [comment]
Closing as inactive.
