### ISSUE TITLE
How to use it correctly in rocketmq-python-client to ensure at least one time or just once

### ISSUE THREAD

**Issue by unclesix06** [messense/rocketmq-python#42]
BUG REPORT

Please describe the issue you observed:
What did you do (The steps to reproduce)?
Example of using the official website pullconsumer or pushconsumer
What did you expect to see?
Spend at least once or just once, and process the msg of the transaction failure, then msg roll back, wait for the next try again
What did you see instead?
read all msg repeatedly every time you start
Please tell us about your environment:
What is your OS?
ubuntu 18.04
What is your client version?
0.4.1
What is your RocketMQ version?
4.5.2
Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
FEATURE REQUEST

Please describe the feature you are requesting.
I want to know the following two usages：
（1）How can I use it properly to ensure that I consume it at least once or just once,
（2）and how the message queue is rolled back when the transaction fails.
Looking forward to your reply，thanks.

**Comment by messense** [comment]
What type of consumer are you using? `PushConsumer` or `PullConsumer`? If you use `PullConsumer` you need to manage offsets by yourself.

**Comment by brett1127** [comment]
![mq](https://user-images.githubusercontent.com/34953483/63842597-7889b680-c9b7-11e9-9725-47d165e79a8b.png)

**Comment by brett1127** [comment]
![image](https://user-images.githubusercontent.com/34953483/63842639-91926780-c9b7-11e9-8c43-01fa360100b3.png)




导入包报这个错,想问下是什么原因?

**Comment by messense** [comment]
@brett1127 暂不支持 Windows 系统。

**Comment by messense** [comment]
Closing as inactive.
