### ISSUE TITLE
PushConsumer的callback方法抛异常，不能重新消费消息

### ISSUE THREAD

**Issue by q2044757581** [messense/rocketmq-python#45]
` 
            def subscribe(self, topic, callback, expression='*'):
            def _on_message(consumer, msg):
            exc = None
            try:
                callback(RecvMessage(msg))
            except Exception as e:
                exc = e
                return _CConsumeStatus.RECONSUME_LATER.value
            finally:
                if exc:
                    raise exc

            return _CConsumeStatus.CONSUME_SUCCESS.value

        ffi_check(dll.Subscribe(self._handle, _to_bytes(topic), _to_bytes(expression)))
        self._register_callback(_on_message)
`

**callback抛异常，消息不能重新消费，finally代码是否有问题，
重写了subscribe，去掉finally也不能重新消费消息，请问下是怎么回事
**

**Comment by messense** [comment]
抛了什么异常？

**Comment by q2044757581** [comment]
> 
> 
> 抛了什么异常？
raise Exception("xxxxx")


我就是想测试一下，抛异常之后，是否可以重新消费。

我看代码里，捕获异常之后，会返回 _CConsumeStatus.RECONSUME_LATER.value

**Comment by messense** [comment]
不能复现：https://github.com/messense/rocketmq-python/pull/46/files
