### ISSUE TITLE
部署消费端进程，会出现不定期重启问题。

### ISSUE THREAD

**Issue by lin9long** [messense/rocketmq-python#50]
重启的时间间隔为1天左右。有办法能定位原因吗？rocketmq-cpp的错误日志只有如下的：
(error):updateTopicRouteInfo: didn't get the session_credentials from any producers and consumers, please re-intialize it[getSessionCredentialsFromOneOfProducerOrConsumer:1100

**Comment by messense** [comment]
重启是什么意思，程序异常退出再被进程管理器启动还是怎么了？有 Python 的异常栈吗？

**Comment by lin9long** [comment]
有后台的守护进程，如果发现进程不存在会自动拉起，python异常栈尝试在外面启动consumer时候捕获，但是没捕获到异常。

**Comment by messense** [comment]
dmesg 看看 kernal 的日志是不是 OOM 啥的被 kill 了？

**Comment by lin9long** [comment]
查了dmesg被kill的日志，时间和进程都对不上，可能是被运维kill掉吗？

**Comment by messense** [comment]
没有遇到过，需要更多的日志、异常信息来排查问题。另外，可以看一下是不是 segfault 了，打开 core dump 等等看会不会产生 core dump 文件。

**Comment by messense** [comment]
Close as inactive.
