### ISSUE TITLE
PULL模式，设置消费的起始位置

### ISSUE THREAD

**Issue by itdarkwater** [messense/rocketmq-python#54]
使用PULL模式消费时，怎么设置消费的起始位置。
我没有找到设值的地方，但是rocketmq本身有提供FROM_FIRST、FROM_LAST、FROM_TIMESTAMP三种回溯模式。

**Comment by messense** [comment]
需要提供一下 RocketMQ 相关的文档，也得看一下 rocketmq-client-cpp 是怎么暴露这些参数的。

**Comment by yehaohao-lw** [comment]
@messense  
consumer = PullConsumer('CID_XXX')
consumer.set_namesrv_domain('http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet')
# For ip and port name server address, use `set_namesrv_addr` method, for example:
# consumer.set_namesrv_addr('127.0.0.1:9887')
consumer.set_session_credentials('XXX', 'XXXX', 'ALIYUN') # No need to call this function if you don't use Aliyun.
consumer.start()

for msg in consumer.pull('YOUR-TOPIC'):
     --每次都是重头开始消费
    print(msg.id, msg.body)

consumer.shutdown()
有什么方法可以设置从上次消费后开始吗

**Comment by messense** [comment]
@yehaohao-lw pull 本来就是设计成手工管理 offset 的，你的需求应该用 pushconsumer 吧
