### ISSUE TITLE
消费模式设置问题

### ISSUE THREAD

**Issue by q2044757581** [messense/rocketmq-python#60]
consumer.set_message_model() 这个方法如果不调的话， 默认的消费模式是什么， 还有调这个方法传入的参数应该是什么， 可以给个例子吗

**Comment by messense** [comment]
http://rocketmq.apache.org/docs/core-concept/

https://github.com/messense/rocketmq-python/blob/75d4ce47561884e338ae7abdd175a928e5e87711/rocketmq/ffi.py#L64-L66

默认：
https://github.com/messense/rocketmq-python/blob/75d4ce47561884e338ae7abdd175a928e5e87711/rocketmq/client.py#L335-L342
