### ISSUE TITLE
Can you invite me to be a maintainer of the RocketMQ PyPI package?

### ISSUE THREAD

**Issue by aaron-ai** [messense/rocketmq-python#71]
@messense  Can you invite me to be a maintainer of the [RocketMQ PyPI package](https://pypi.org/project/rocketmq/)? Since the community are developing the new python client in [rocketmq-clients](https://github.com/apache/rocketmq-clients).

Here is my username: aaron-ai, Thank you!

**Comment by messense** [comment]
Invitation sent.
